Repository Capstone-Design-A/back, pull requests merged in 2024-05, with the labels that each got.

#24 [config] 임시로 모든 cors를 허용하는 설정을 함
  src/main/java/com/example/capstone/config/WebConfig.java
Labels: 설정

#26 Test 테스트 코드 수정 #25
  src/main/java/com/example/capstone/item/Item.java
  src/test/java/com/example/capstone/item/service/ItemServiceTest.java
Labels: 수정

#32 [FIX] nginx.conf options 요청에 모든 orign에 대해 cors 허용하도록 수정
  .platform/nginx.conf
Labels: 설정

#33 [REFACTOR] Item에 deadline 속성 추가로 인해 Converter와 DTO를 수정한다 #28
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
  src/main/java/com/example/capstone/item/dto/ItemResponseDTO.java
Labels: 수정

#35 [CONFIG] QueryDSL 설정 #34
  build.gradle
  src/main/java/com/example/capstone/config/QueryDslConfig.java
Labels: 설정

#36 [Feat] 메인페이지 api 구현 #27
  src/main/java/com/example/capstone/item/repository/ItemRepository.java
  src/main/java/com/example/capstone/item/repository/ItemRepositoryCustom.java
  src/main/java/com/example/capstone/item/repository/ItemRepositoryImpl.java
  src/main/java/com/example/capstone/page/PageController.java
  src/main/java/com/example/capstone/page/PageResponseDTO.java
  src/main/java/com/example/capstone/page/PageService.java
  src/test/java/com/example/capstone/item/service/ItemServiceTest.java
Labels: 기능, 수정

#40 feat - 마감임박 상품 조회시 취소된 주문상품은 제외되도록 수정
  src/main/java/com/example/capstone/item/repository/ItemRepository.java
  src/main/java/com/example/capstone/page/PageService.java
Labels: 리팩토링, 버그, 수정

#45 Feat detail of item search
  .gitignore
  build.gradle
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/item/Item.java
  src/main/java/com/example/capstone/item/controller/ItemController.java
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
  src/main/java/com/example/capstone/item/converter/ItemImageConverter.java
  src/main/java/com/example/capstone/item/dto/GroupItemResponseDTO.java
  src/main/java/com/example/capstone/item/dto/ItemImageResponseDTO.java
  src/main/java/com/example/capstone/item/dto/ItemResponseDTO.java
  src/main/java/com/example/capstone/item/service/ItemService.java
  src/test/java/com/example/capstone/item/repository/ItemRepositoryTest.java
  src/test/java/com/example/capstone/item/service/ItemServiceTest.java
Labels: 기능

#50 [Feat] search inquiry
  .gitignore
  build.gradle
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/inquiry/controller/InquiryController.java
  src/main/java/com/example/capstone/inquiry/converter/InquiryConverter.java
  src/main/java/com/example/capstone/inquiry/dto/InquiryResponseDTO.java
  src/main/java/com/example/capstone/inquiry/repository/InquiryRepository.java
  src/main/java/com/example/capstone/inquiry/service/InquiryService.java
  src/main/java/com/example/capstone/member/converter/MemberConverter.java
  src/main/java/com/example/capstone/member/dto/MemberResponseDTO.java
  src/main/java/com/example/capstone/seller/SellerResponseDTO.java
  src/main/java/com/example/capstone/seller/converter/SellerConverter.java
  src/test/java/com/example/capstone/grouppurchaseitem/repository/groupPurchaseItemRepositoryTest.java
  src/test/java/com/example/capstone/inquiry/inquiryServiceTest.java
Labels: 기능

#54 Modify InquiryServiceTest
  src/main/java/com/example/capstone/seller/Post.java
  src/test/java/com/example/capstone/inquiry/inquiryServiceTest.java
  src/test/java/com/example/capstone/inquiry/service/inquiryServiceTest.java
Labels: 수정

#56 Feat search review #55
  src/main/java/com/example/capstone/inquiry/controller/InquiryController.java
  src/main/java/com/example/capstone/inquiry/service/InquiryService.java
  src/main/java/com/example/capstone/inquiry/service/InquiryServiceImpl.java
  src/main/java/com/example/capstone/item/Review.java
  src/main/java/com/example/capstone/item/controller/ReviewController.java
  src/main/java/com/example/capstone/item/converter/ReviewConverter.java
  src/main/java/com/example/capstone/item/dto/ReviewResponseDTO.java
  src/main/java/com/example/capstone/item/repository/ReviewRepository.java
  src/main/java/com/example/capstone/item/service/ReviewService.java
  src/main/java/com/example/capstone/item/service/ReviewServiceImpl.java
  src/main/java/com/example/capstone/order/OrderItem.java
  src/main/java/com/example/capstone/order/common/OrderStatus.java
  src/main/resources/application-local.yml
  src/test/java/com/example/capstone/groupPurchaseItem/repository/groupPurchaseItemRepositoryTest.java
  src/test/java/com/example/capstone/groupPurchaseItem/service/groupPurchaseItemServiceTest.java
  src/test/java/com/example/capstone/inquiry/service/InquiryServiceTest.java
  src/test/java/com/example/capstone/review/ReviewRepositoryTest.java
Labels: 기능

#63 [fix] item 연관 관계 수정 #62
  src/main/java/com/example/capstone/item/Item.java
  src/main/java/com/example/capstone/item/repository/ItemRepository.java
  src/main/java/com/example/capstone/order/repository/custom/OrderItemRepositoryImpl.java
  src/main/java/com/example/capstone/seller/service/SellerManagementServiceImpl.java
  src/main/resources/application.yml
  src/test/java/com/example/capstone/dummy/addDummyTest.java
  src/test/java/com/example/capstone/order/repository/OrderItemRepositoryTest.java
  src/test/java/resource/application.yml
Labels: 수정

#66 [Feat] 판매자관리api #46
  src/main/java/com/example/capstone/order/repository/custom/OrderItemRepositoryImpl.java
  src/main/java/com/example/capstone/seller/converter/SellerManagementConverter.java
  src/main/java/com/example/capstone/seller/dto/SellerResponseDTO.java
Labels: 수정

#88 Feat 구독 #71
  src/main/java/com/example/capstone/apiPayload/ApiResponse.java
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/capstone/common/ValidateUtil.java
  src/main/java/com/example/capstone/member/Member.java
  src/main/java/com/example/capstone/member/controller/SubscriptionController.java
  src/main/java/com/example/capstone/member/converter/SubscriptionConverter.java
  src/main/java/com/example/capstone/member/dto/SubscriptionResponseDTO.java
  src/main/java/com/example/capstone/member/repository/SubscriptionRepository.java
  src/main/java/com/example/capstone/member/service/SubscriptionService.java
  src/test/java/com/example/capstone/member/service/SubscriptionServiceTest.java
Labels: 기능

#92 [FIX]modify search details of groupItem
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
  src/main/java/com/example/capstone/item/converter/ItemImageConverter.java
  src/main/java/com/example/capstone/item/dto/ItemImageResponseDTO.java
  src/main/java/com/example/capstone/item/dto/ItemResponseDTO.java
Labels: 수정

#104 [FIX]인증된 멤버의 ID를 컨트롤러에서 조회할 수 있도록 수정
  src/main/java/com/example/capstone/member/controller/AlarmController.java
  src/main/java/com/example/capstone/security/dto/MemberSecurityDTO.java
  src/main/java/com/example/capstone/security/filter/LoginFilter.java
  src/main/java/com/example/capstone/security/filter/RefreshTokenFilter.java
  src/main/java/com/example/capstone/security/handler/LoginSuccessHandler.java
  src/main/java/com/example/capstone/security/service/MemberDetailsService.java
Labels: 수정

#105 AuthenticatedMemberUtil 추가
  src/main/java/com/example/capstone/member/controller/AlarmController.java
  src/main/java/com/example/capstone/util/AuthenticatedMemberUtil.java
Labels: 수정

#107 게시판 crud api 구현 #70
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/capstone/aws/s3/AmazonS3Util.java
  src/main/java/com/example/capstone/common/ValidateUtil.java
  src/main/java/com/example/capstone/config/SecurityConfig.java
  src/main/java/com/example/capstone/member/Member.java
  src/main/java/com/example/capstone/member/controller/SubscriptionController.java
  src/main/java/com/example/capstone/post/Post.java
  src/main/java/com/example/capstone/post/PostImage.java
  src/main/java/com/example/capstone/post/controller/PostController.java
  src/main/java/com/example/capstone/post/converter/PostConverter.java
  src/main/java/com/example/capstone/post/dto/PostRequestDTO.java
  src/main/java/com/example/capstone/post/dto/PostResponseDTO.java
  src/main/java/com/example/capstone/post/repository/PostImageRepository.java
  src/main/java/com/example/capstone/post/repository/PostRepository.java
  src/main/java/com/example/capstone/post/service/PostService.java
  src/main/java/com/example/capstone/post/service/PostServiceImpl.java
  src/main/java/com/example/capstone/seller/Seller.java
  src/main/java/com/example/capstone/seller/controller/SellerManagementController.java
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 기능

#108 [feat] 판매자 소개 페이지 조회 api 구현 #69
  src/main/java/com/example/capstone/common/QueryService.java
  src/main/java/com/example/capstone/member/service/SubscriptionService.java
  src/main/java/com/example/capstone/page/PageController.java
  src/main/java/com/example/capstone/page/PageConverter.java
  src/main/java/com/example/capstone/page/PageResponseDTO.java
  src/main/java/com/example/capstone/page/PageService.java
  src/main/java/com/example/capstone/post/converter/PostConverter.java
  src/main/java/com/example/capstone/post/dto/PostResponseDTO.java
  src/main/java/com/example/capstone/post/service/PostService.java
  src/main/java/com/example/capstone/post/service/PostServiceImpl.java
  src/test/java/com/example/capstone/member/service/SubscriptionServiceTest.java
Labels: 기능

#112 [FIX] CORS 문제를 해결하기 위해서 ./platform/nginx/nginx.conf을 수정
  .platform/nginx.conf
Labels: 버그

#113 [Bug] $allowed origin 추가 및 디렉토리 구조 수정 #109
  .platform/nginx/nginx.conf
Labels: 버그

#120 [Feat] 장바구니에 아이템을 담는 기능 구현 #106
  src/main/java/com/example/capstone/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/capstone/exception/ExceptionAdvice.java
  src/main/java/com/example/capstone/item/controller/ItemController.java
  src/main/java/com/example/capstone/item/service/ItemService.java
  src/main/java/com/example/capstone/item/service/ItemServiceImpl.java
  src/main/java/com/example/capstone/order/Cart.java
  src/main/java/com/example/capstone/order/controller/CartController.java
  src/main/java/com/example/capstone/order/converter/CartConverter.java
  src/main/java/com/example/capstone/order/dto/CartRequestDTO.java
  src/main/java/com/example/capstone/order/service/CartService.java
  src/main/java/com/example/capstone/order/service/CartServiceImpl.java
  src/main/java/com/example/capstone/page/PageService.java
  src/main/java/com/example/capstone/security/util/JWTUtil.java
  src/main/resources/application.yml
  src/test/java/com/example/capstone/cart/repository/CartRepositoryTest.java
  src/test/java/com/example/capstone/item/service/ItemServiceTest.java
Labels: 기능

#121 [feat] 구매자 -> 판매자 전환 api 구현 #119
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/capstone/member/Member.java
  src/main/java/com/example/capstone/member/controller/MemberController.java
  src/main/java/com/example/capstone/member/converter/MemberConverter.java
  src/main/java/com/example/capstone/member/dto/MemberResponseDTO.java
  src/main/java/com/example/capstone/member/service/MemberService.java
  src/main/java/com/example/capstone/seller/controller/SellerManagementController.java
  src/test/java/com/example/capstone/member/service/MemberServiceTest.java
Labels: 기능

#124 [Feat] 회원가입 기능 추가 #122
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/capstone/member/Member.java
  src/main/java/com/example/capstone/member/common/MemberValidator.java
  src/main/java/com/example/capstone/member/controller/MemberController.java
  src/main/java/com/example/capstone/member/converter/MemberConverter.java
  src/main/java/com/example/capstone/member/dto/AddressDTO.java
  src/main/java/com/example/capstone/member/dto/MemberRequestDTO.java
  src/main/java/com/example/capstone/member/dto/MemberResponseDTO.java
  src/main/java/com/example/capstone/member/repository/AddressRepository.java
  src/main/java/com/example/capstone/member/repository/MemberRepository.java
  src/main/java/com/example/capstone/member/service/MemberService.java
  src/main/java/com/example/capstone/member/service/MemberServiceImpl.java
  src/main/java/com/example/capstone/order/controller/CartController.java
  src/main/java/com/example/capstone/order/dto/CartResponseDTO.java
  src/main/resources/application.yml
  src/test/java/com/example/capstone/dummy/addDummyTest.java
  src/test/java/com/example/capstone/member/service/MemberServiceTest.java
  src/test/java/com/example/capstone/member/util/MemberValidatorTest.java
Labels: 기능

#127 [fix] 상품 등록 api 수정 #118
  src/main/java/com/example/capstone/item/controller/ItemController.java
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
  src/main/java/com/example/capstone/item/dto/ItemRequestDTO.java
  src/main/java/com/example/capstone/item/dto/ItemResponseDTO.java
  src/main/java/com/example/capstone/item/service/ItemService.java
  src/main/java/com/example/capstone/item/service/ItemServiceImpl.java
Labels: 수정

#130 [feat] 구독 여부 확인 api 구현 #129
  src/main/java/com/example/capstone/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/capstone/common/QueryService.java
  src/main/java/com/example/capstone/member/controller/SubscriptionController.java
  src/main/java/com/example/capstone/member/service/SubscriptionService.java
Labels: 기능

#131 Feat 상품 등록 api #118
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/aws/s3/AmazonS3Util.java
  src/main/java/com/example/capstone/common/QueryService.java
  src/main/java/com/example/capstone/item/Item.java
  src/main/java/com/example/capstone/item/ItemImage.java
  src/main/java/com/example/capstone/item/controller/ItemController.java
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
  src/main/java/com/example/capstone/item/dto/ItemRequestDTO.java
  src/main/java/com/example/capstone/item/dto/ItemResponseDTO.java
  src/main/java/com/example/capstone/item/repository/ItemImageRepository.java
  src/main/java/com/example/capstone/item/service/ItemService.java
  src/main/java/com/example/capstone/item/service/ItemServiceImpl.java
  src/main/java/com/example/capstone/post/PostImage.java
  src/main/java/com/example/capstone/post/dto/PostRequestDTO.java
  src/main/java/com/example/capstone/post/service/PostServiceImpl.java
  src/main/java/com/example/capstone/seller/service/SellerManagementServiceImpl.java
Labels: 기능

#132 [Feat] modify member #125
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/capstone/member/Address.java
  src/main/java/com/example/capstone/member/Member.java
  src/main/java/com/example/capstone/member/common/MemberValidator.java
  src/main/java/com/example/capstone/member/controller/MemberController.java
  src/main/java/com/example/capstone/member/converter/MemberConverter.java
  src/main/java/com/example/capstone/member/dto/AddressDTO.java
  src/main/java/com/example/capstone/member/dto/MemberRequestDTO.java
  src/main/java/com/example/capstone/member/repository/AddressRepository.java
  src/main/java/com/example/capstone/member/repository/MemberRepository.java
  src/main/java/com/example/capstone/member/service/MemberService.java
  src/main/java/com/example/capstone/member/service/MemberServiceImpl.java
  src/main/java/com/example/capstone/seller/converter/SellerConverter.java
  src/test/java/com/example/capstone/member/util/MemberValidatorTest.java
Labels: 기능, 수정

#134 [FEAT]구독한 판매자 목록 조회 #133
  src/main/java/com/example/capstone/common/QueryService.java
  src/main/java/com/example/capstone/inquiry/dto/InquiryResponseDTO.java
  src/main/java/com/example/capstone/member/dto/MemberResponseDTO.java
  src/main/java/com/example/capstone/member/service/MemberService.java
  src/main/java/com/example/capstone/seller/SellerResponseDTO.java
  src/main/java/com/example/capstone/seller/controller/SellerController.java
  src/main/java/com/example/capstone/seller/controller/SellerManagementController.java
  src/main/java/com/example/capstone/seller/converter/SellerConverter.java
  src/main/java/com/example/capstone/seller/dto/TempSellerResponseDTO.java
  src/main/java/com/example/capstone/seller/repository/SellerRepository.java
  src/main/java/com/example/capstone/seller/service/SellerService.java
  src/main/java/com/example/capstone/seller/service/SellerServiceImpl.java
  src/test/java/com/example/capstone/cart/repository/CartRepositoryTest.java
  src/test/java/com/example/capstone/member/repository/MemberRepositoryTest.java
  src/test/java/com/example/capstone/seller/repository/SellerRepositoryTest.java
Labels: 기능

#136 Feat 판매 마감이 얼마남지 않은 상품 조회 api #73
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/common/QueryService.java
  src/main/java/com/example/capstone/item/repository/ItemRepository.java
  src/main/java/com/example/capstone/item/repository/ItemRepositoryImpl.java
  src/main/java/com/example/capstone/item/repository/custom/ItemRepositoryCustom.java
  src/main/java/com/example/capstone/item/repository/custom/ItemRepositoryImpl.java
  src/main/java/com/example/capstone/order/repository/custom/OrderItemRepositoryImpl.java
  src/main/java/com/example/capstone/seller/controller/SellerManagementController.java
  src/main/java/com/example/capstone/seller/converter/SellerManagementConverter.java
  src/main/java/com/example/capstone/seller/dto/SellerResponseDTO.java
  src/main/java/com/example/capstone/seller/repository/custom/SellerRepositoryCustom.java
  src/main/java/com/example/capstone/seller/repository/custom/SellerRepositoryImpl.java
  src/main/java/com/example/capstone/seller/service/SellerManagementService.java
  src/main/java/com/example/capstone/seller/service/SellerManagementServiceImpl.java
  src/main/java/com/example/capstone/validation/annotation/CheckOrder.java
  src/main/java/com/example/capstone/validation/annotation/CheckPage.java
  src/main/java/com/example/capstone/validation/annotation/CheckSort.java
  src/main/java/com/example/capstone/validation/annotation/ExistCategories.java
  src/main/java/com/example/capstone/validation/validator/CategoriesExistValidator.java
  src/main/java/com/example/capstone/validation/validator/CheckPageValidator.java
  src/main/java/com/example/capstone/validation/validator/OrderParameterValidator.java
  src/main/java/com/example/capstone/validation/validator/SortParameterValidator.java
Labels: 기능

#137 [FIX]임시 멤버 삭제, 회원 가입시 검증 추가
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
  src/main/java/com/example/capstone/item/dto/ItemResponseDTO.java
  src/main/java/com/example/capstone/member/controller/MemberController.java
  src/main/java/com/example/capstone/member/service/MemberServiceImpl.java
  src/main/java/com/example/capstone/order/converter/CartConverter.java
  src/main/java/com/example/capstone/order/dto/CartResponseDTO.java
  src/main/java/com/example/capstone/order/repository/CartRepository.java
  src/main/java/com/example/capstone/order/service/CartServiceImpl.java
  src/test/java/com/example/capstone/cart/repository/CartRepositoryTest.java
Labels: 수정

#146 [refactor] 판매자 전환 api 수정 #142
  src/main/java/com/example/capstone/aws/s3/AmazonS3Util.java
  src/main/java/com/example/capstone/config/AmazonConfig.java
  src/main/java/com/example/capstone/member/controller/MemberController.java
  src/main/java/com/example/capstone/member/dto/MemberRequestDTO.java
  src/main/java/com/example/capstone/member/service/MemberService.java
  src/main/java/com/example/capstone/member/service/MemberServiceImpl.java
  src/main/java/com/example/capstone/seller/repository/custom/SellerRepositoryImpl.java
  src/main/resources/application.yml
Labels: 리팩토링
