Repository Capstone-Design-A/back, pull requests merged in 2024-06, with the labels that each got.

#147 [FEAT]공동 구매 상품 현황 조회
  src/main/java/com/example/capstone/common/UtilList.java
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
  src/main/java/com/example/capstone/item/dto/ItemResponseDTO.java
  src/main/java/com/example/capstone/order/controller/OrderItemController.java
  src/main/java/com/example/capstone/order/converter/OrderItemConverter.java
  src/main/java/com/example/capstone/order/dto/OrderItemResponseDTO.java
  src/main/java/com/example/capstone/order/repository/OrderItemRepository.java
  src/main/java/com/example/capstone/order/service/OrderItemService.java
  src/main/java/com/example/capstone/order/service/OrderItemServiceImpl.java
Labels: 기능

#149 [FIX] 인증이 필요한 api에 토큰 요구 및 알람 조회 시 읽음 처리
  src/main/java/com/example/capstone/item/controller/ItemController.java
  src/main/java/com/example/capstone/member/Alarm.java
  src/main/java/com/example/capstone/member/controller/AlarmController.java
  src/main/java/com/example/capstone/member/service/AlarmService.java
Labels: 수정

#153 [FIX] 요청 바디 사이즈 제한을 200M으로 설정
  .platform/nginx/conf.d/client_max_body_size.conf
  capstoneFront/front
Labels: 수정

#154 [FIX]이미지 대표 URL을 처음 저장된 이미지로 저장하기
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
Labels: 수정

#156 [Fix] 이미지 관련 변경사항 초기화 # 150
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
  src/main/java/com/example/capstone/item/converter/ItemImageConverter.java
Labels: 수정

#157 [FIX]대표 이미지 임시 처리 #150
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
  src/main/java/com/example/capstone/item/converter/ItemImageConverter.java
Labels: 수정

#162 [FIX] 장바구니의 insert시 중복 체크 #150
  src/main/java/com/example/capstone/order/Cart.java
  src/main/java/com/example/capstone/order/repository/CartRepository.java
  src/main/java/com/example/capstone/order/service/CartServiceImpl.java
Labels: 수정

#165 [FIX] 이미지 등록 임시 처리한 부분 원래대로 돌리기 #150
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
Labels: 수정

#166 [FIX]상품 이미지와 설명이미지 뒤바뀜 수정#150
  src/main/java/com/example/capstone/item/converter/ItemConverter.java
Labels: 수정

#169 [FEAT]유저의 비밀번호 체크 API #168
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/member/controller/MemberController.java
  src/main/java/com/example/capstone/member/service/MemberService.java
  src/main/java/com/example/capstone/member/service/MemberServiceImpl.java
Labels: 기능

#173 [FEAT] 장바구니 비우기 및 장바구니 아이템 수량 조절 API 완성 #170
  src/main/java/com/example/capstone/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/example/capstone/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/capstone/order/controller/CartController.java
  src/main/java/com/example/capstone/order/dto/CartRequestDTO.java
  src/main/java/com/example/capstone/order/repository/CartRepository.java
  src/main/java/com/example/capstone/order/service/CartService.java
  src/main/java/com/example/capstone/order/service/CartServiceImpl.java
  src/test/java/com/example/capstone/member/service/MemberServiceTest.java
Labels: 기능

#175 [FEAT]문의 작성 API 구현 #174
  src/main/java/com/example/capstone/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/example/capstone/inquiry/Inquiry.java
  src/main/java/com/example/capstone/inquiry/controller/InquiryController.java
  src/main/java/com/example/capstone/inquiry/dto/InquiryRequestDTO.java
  src/main/java/com/example/capstone/inquiry/service/InquiryService.java
  src/main/java/com/example/capstone/inquiry/service/InquiryServiceImpl.java
Labels: 기능

#177 [refactor] 역직렬화 설정 대신 다른 @ModelAttribute로 해결 #172
  src/main/java/com/example/capstone/common/OrderedMultipartFileDTO.java
  src/main/java/com/example/capstone/item/ItemImage.java
  src/main/java/com/example/capstone/item/common/ImageType.java
  src/main/java/com/example/capstone/item/controller/ItemController.java
  src/main/java/com/example/capstone/item/converter/ItemImageConverter.java
  src/main/java/com/example/capstone/item/dto/ItemImageResponseDTO.java
  src/main/java/com/example/capstone/item/dto/ItemRequestDTO.java
  src/main/java/com/example/capstone/item/service/ItemService.java
  src/main/java/com/example/capstone/item/service/ItemServiceImpl.java
Labels: 수정, 설계
